/**
 * withViroVisionOS.ts
 *
 * Expo config plugin that adds a visionOS target to your app's Xcode project.
 *
 * What it does:
 *   1. Writes the SwiftUI App entry point (ViroVisionApp.swift) into the target folder
 *   2. Adds a visionOS pod target to the Podfile
 *   3. Creates a visionOS Xcode target in the .pbxproj with correct SDK + build settings
 *
 * Usage in app.json:
 *   {
 *     "plugins": [
 *       ["@reactvision/react-viro", { ... }],
 *       "@reactvision/react-viro/plugins/withViroVisionOS"
 *     ]
 *   }
 *
 * After running `expo prebuild`, run `pod install` in ios/ then build the
 * <AppName>Vision target in Xcode targeting the visionOS simulator.
 */

import {
  ConfigPlugin,
  withDangerousMod,
  withXcodeProject,
  withPlugins,
  WarningAggregator,
} from "@expo/config-plugins";
import fs from "fs";
import path from "path";

// ─── Constants ────────────────────────────────────────────────────────────────

const TARGET_SUFFIX = "Vision";
const VISIONOS_DEPLOYMENT_TARGET = "1.0";
const PODFILE_MARKER = "# viro-visionos-target";

// ─── Swift App entry point template ──────────────────────────────────────────

function viroVisionAppSwift(targetName: string, bundleId: string): string {
  return `// ViroVisionApp.swift
// Auto-generated by @reactvision/react-viro — DO NOT EDIT MANUALLY.
// Re-generated on every expo prebuild run.

import SwiftUI
import ViroReact

@main
struct ${targetName}App: App {
    /// Current immersion style — driven by ViroVisionOSModule.enterImmersiveSpace(style).
    @State private var immersionStyle: ImmersionStyle = .mixed

    var body: some Scene {
        // Main 2D window (hosts React Native UI if needed, or acts as launch host).
        WindowGroup {
            ViroVisionLaunchView()
                .viroImmersiveSpaceController()
        }

        // The Viro immersive rendering space.
        // Opened via ViroVisionOSModule.enterImmersiveSpace() from JavaScript.
        ImmersiveSpace(id: ViroImmersiveSpace.id) {
            ViroImmersiveSpaceView()
        }
        .immersionStyle(selection: $immersionStyle, in: .mixed, .full, .progressive)
    }
}

/// Minimal launch view displayed in the 2D window.
/// Replace with your own SwiftUI content or a React Native root view.
struct ViroVisionLaunchView: View {
    @State private var isImmersed = false

    var body: some View {
        VStack(spacing: 20) {
            Text("ReactVision AR")
                .font(.largeTitle)
                .fontWeight(.bold)

            Button(isImmersed ? "Exit Immersive Space" : "Enter Immersive Space") {
                Task {
                    if isImmersed {
                        await ViroImmersiveCoordinator.shared.exit()
                    } else {
                        await ViroImmersiveCoordinator.shared.enter(styleString: "mixed")
                    }
                    isImmersed.toggle()
                }
            }
            .buttonStyle(.borderedProminent)
        }
        .padding(40)
    }
}
`;
}

// ─── 1. Write Swift files ─────────────────────────────────────────────────────

const withVisionOSSwiftFiles: ConfigPlugin = (config) => {
  return withDangerousMod(config, [
    "ios",
    async (newConfig) => {
      const root = newConfig.modRequest.platformProjectRoot;
      const projectName = newConfig.modRequest.projectName;
      const targetName = `${projectName}${TARGET_SUFFIX}`;
      const bundleId = `${newConfig.ios?.bundleIdentifier ?? "com.example"}.vision`;
      const targetDir = path.join(root, targetName);

      if (!fs.existsSync(targetDir)) {
        fs.mkdirSync(targetDir, { recursive: true });
      }

      // Always overwrite — it's auto-generated.
      fs.writeFileSync(
        path.join(targetDir, "ViroVisionApp.swift"),
        viroVisionAppSwift(targetName, bundleId),
        "utf-8"
      );

      return newConfig;
    },
  ]);
};

// ─── 2. Podfile target block ──────────────────────────────────────────────────

const withVisionOSPodfile: ConfigPlugin = (config) => {
  return withDangerousMod(config, [
    "ios",
    async (newConfig) => {
      const root = newConfig.modRequest.platformProjectRoot;
      const projectName = newConfig.modRequest.projectName;
      const targetName = `${projectName}${TARGET_SUFFIX}`;
      const podfilePath = path.join(root, "Podfile");

      let podfile = fs.readFileSync(podfilePath, "utf-8");

      // Idempotent — skip if already present.
      if (podfile.includes(PODFILE_MARKER)) return newConfig;

      const podBlock = [
        "",
        PODFILE_MARKER,
        `# ViroKit (iOS-only) and ViroReact (ObjC) are excluded until ViroKit`,
        `# is compiled for xros SDK (Week 2). The POC uses Metal + CompositorServices directly.`,
        `target '${targetName}' do`,
        `end`,
        "",
      ].join("\n");

      fs.writeFileSync(podfilePath, podfile + podBlock, "utf-8");
      return newConfig;
    },
  ]);
};

// ─── 3. Xcode target ─────────────────────────────────────────────────────────

const withVisionOSXcodeTarget: ConfigPlugin = (config) => {
  return withXcodeProject(config, (newConfig) => {
    const pbxProject = newConfig.modResults;
    const projectName = newConfig.modRequest.projectName;
    const targetName = `${projectName}${TARGET_SUFFIX}`;
    const bundleId = `${newConfig.ios?.bundleIdentifier ?? "com.example"}.vision`;
    const targetDir = targetName; // relative path inside ios/

    // ── Check for existing target ────────────────────────────────────────────
    const nativeTargets = pbxProject.pbxNativeTargetSection() as Record<string, any>;
    const alreadyExists = Object.values(nativeTargets).some(
      (t) =>
        t &&
        typeof t === "object" &&
        (t.name === targetName || t.name === `"${targetName}"`)
    );
    if (alreadyExists) return newConfig;

    // ── Add the target (creates PBX phases + config list) ────────────────────
    const target = (pbxProject as any).addTarget(
      targetName,
      "application",
      targetDir,
      bundleId
    );

    if (!target) {
      WarningAggregator.addWarningIOS(
        "withViroVisionOS",
        `Failed to add visionOS target "${targetName}" to Xcode project. ` +
          "Add it manually in Xcode: File → New → Target → visionOS → App."
      );
      return newConfig;
    }

    // ── Set visionOS build settings on every config for this target ──────────
    const configList = pbxProject.pbxXCBuildConfigurationSection() as Record<string, any>;

    for (const conf of Object.values(configList)) {
      if (!conf || typeof conf !== "object" || !conf.buildSettings) continue;

      const name: string = conf.buildSettings.PRODUCT_NAME;
      if (!name) continue;
      const normalized = name.replace(/^"(.*)"$/, "$1");
      if (normalized !== targetName) continue;

      const bs = conf.buildSettings;

      // visionOS SDK
      bs.SDKROOT = "xros";
      bs.SUPPORTED_PLATFORMS = '"xros xrsimulator"';
      bs[`"DEPLOYMENT_TARGET[sdk=xros*]"`] = `"${VISIONOS_DEPLOYMENT_TARGET}"`;
      bs.TARGETED_DEVICE_FAMILY = '"7"';

      // Swift
      bs.SWIFT_VERSION = '"5.0"';
      bs.CLANG_ENABLE_MODULES = "YES";

      // Runpath for dynamic frameworks (CocoaPods)
      bs.LD_RUNPATH_SEARCH_PATHS = '"$(inherited) @executable_path/Frameworks"';

      // Embed Swift standard libraries
      bs.ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = "YES";

      // App-specific
      bs.PRODUCT_BUNDLE_IDENTIFIER = `"${bundleId}"`;
      bs.INFOPLIST_FILE = `"${targetDir}/Info.plist"`;
      bs.GENERATE_INFOPLIST_FILE = "NO";
      bs.ASSETCATALOG_COMPILER_APPICON_NAME = "AppIcon";

      // Don't strip Swift symbols in debug
      if (conf.name === "Debug") {
        bs.SWIFT_OPTIMIZATION_LEVEL = '"-Onone"';
        bs.SWIFT_ACTIVE_COMPILATION_CONDITIONS = "DEBUG";
      }
    }

    // ── Write Info.plist for the visionOS target ──────────────────────────────
    // (written during the dangerous mod pass — cannot write files here)
    // Logged as a reminder.
    WarningAggregator.addWarningIOS(
      "withViroVisionOS",
      `visionOS target "${targetName}" added. ` +
        `Run "pod install" in ios/ then build the target in Xcode. ` +
        `An Info.plist will be auto-generated by Xcode for the new target.`
    );

    return newConfig;
  });
};

// ─── 4. Info.plist for visionOS target ───────────────────────────────────────

const INFOPLIST_CONTENT = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key>
    <string>$(DEVELOPMENT_LANGUAGE)</string>
    <key>CFBundleExecutable</key>
    <string>$(EXECUTABLE_NAME)</string>
    <key>CFBundleIdentifier</key>
    <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>$(PRODUCT_NAME)</string>
    <key>CFBundlePackageType</key>
    <string>$(PRODUCT_BUNDLE_PACKAGE_TYPE)</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>CFBundleVersion</key>
    <string>1</string>
    <key>UIApplicationSceneManifest</key>
    <dict>
        <key>UIApplicationSupportsMultipleScenes</key>
        <true/>
    </dict>
    <key>NSHandsTrackingUsageDescription</key>
    <string>Hand tracking is used for interaction in AR experiences.</string>
</dict>
</plist>
`;

const withVisionOSInfoPlist: ConfigPlugin = (config) => {
  return withDangerousMod(config, [
    "ios",
    async (newConfig) => {
      const root = newConfig.modRequest.platformProjectRoot;
      const projectName = newConfig.modRequest.projectName;
      const targetName = `${projectName}${TARGET_SUFFIX}`;
      const targetDir = path.join(root, targetName);

      if (!fs.existsSync(targetDir)) {
        fs.mkdirSync(targetDir, { recursive: true });
      }

      const plistPath = path.join(targetDir, "Info.plist");
      if (!fs.existsSync(plistPath)) {
        fs.writeFileSync(plistPath, INFOPLIST_CONTENT, "utf-8");
      }

      return newConfig;
    },
  ]);
};

// ─── Main export ──────────────────────────────────────────────────────────────

export const withViroVisionOS: ConfigPlugin = (config) => {
  return withPlugins(config, [
    withVisionOSSwiftFiles,
    withVisionOSInfoPlist,
    withVisionOSPodfile,
    withVisionOSXcodeTarget,
  ]);
};

export default withViroVisionOS;
