package com.viromedia.bridge.module;

import android.app.Activity;
import android.content.Intent;
import android.os.Handler;
import android.os.Looper;

import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.internal.featureflags.ReactNativeFeatureFlags;
import com.facebook.react.internal.featureflags.ReactNativeFeatureFlagsDefaults;

/**
 * VRLauncherModule
 *
 * Registered by ReactViroPackage when ViroPlatform.QUEST is active.
 * Launches a VRActivity (generated by the withViroAndroid Expo plugin) that
 * carries com.oculus.intent.category.VR, causing Horizon OS to grant exclusive
 * OpenXR display access for stereo VR rendering.
 *
 * JS usage:
 *   import { NativeModules } from 'react-native';
 *   NativeModules.VRLauncher?.launchVRScene();
 */
public class VRLauncherModule extends ReactContextBaseJavaModule {

    private static final String MODULE_NAME = "VRLauncher";
    // Component name that VRActivity will mount.
    // Must match AppRegistry.registerComponent("VRQuestScene", ...) in the app's entry.
    private static final String VR_COMPONENT = "VRQuestScene";

    public VRLauncherModule(ReactApplicationContext reactContext) {
        super(reactContext);
    }

    @Override
    public String getName() {
        return MODULE_NAME;
    }

    @ReactMethod
    public void launchVRScene() {
        // Called from JS — Hermes is running and all startup feature flags are already
        // cached in C++. Setting dangerouslyForceOverride here is safe: it replaces the
        // C++ accessor with our Java-backed provider, but cached startup flags are
        // unaffected. skipActivityIdentityAssertionOnHostPause has not been read yet
        // (it is only read in ReactHostImpl.onHostPause, triggered after startActivity).
        try {
            ReactNativeFeatureFlags.INSTANCE.dangerouslyForceOverride(
                new ReactNativeFeatureFlagsDefaults() {
                    @Override
                    public boolean skipActivityIdentityAssertionOnHostPause() { return true; }
                    // dangerouslyForceOverride replaces the C++ provider, so all uncached
                    // reads now go through this provider. The Expo app uses ReactHost
                    // (bridgeless API) but dangerouslyForceOverride resets the JVM and C++
                    // caches. We must return true for the three New Architecture flags so
                    // that ReactActivityDelegate.onCreate() and ReactDelegate.loadApp() /
                    // onHostResume() take the bridgeless path instead of the old-arch path.
                    @Override
                    public boolean enableBridgelessArchitecture() { return true; }
                    @Override
                    public boolean enableFabricRenderer() { return true; }
                    @Override
                    public boolean useTurboModules() { return true; }
                }
            );
        } catch (Exception ignored) {}

        ReactApplicationContext ctx = getReactApplicationContext();
        try {
            Class<?> vrActivityClass = Class.forName(
                ctx.getPackageName() + ".VRActivity"
            );
            Intent intent = new Intent(ctx, vrActivityClass);
            intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            ctx.startActivity(intent);
        } catch (ClassNotFoundException e) {
            throw new RuntimeException(
                "VRActivity not found in package " + ctx.getPackageName() + ". " +
                "Ensure @reactvision/react-viro plugin is configured with xRMode: [\"QUEST\"] " +
                "and you have run expo prebuild."
            );
        }
    }

    /**
     * Finish any live VRActivity in this process, returning the user to whatever
     * Activity is below it in the task (typically MainActivity, the panel app).
     *
     * Why we don't use {@code getReactApplicationContext().getCurrentActivity()}:
     *   In dual-Activity Quest setups the ReactHost lifecycle is binary-state.
     *   {@code ReactHost.onHostResume(VRActivity)} doesn't refire if MainActivity
     *   already transitioned the host to RESUMED, so {@code currentActivity} on
     *   the React context can stay pointed at MainActivity even while VRActivity
     *   is foreground in the immersive compositor. Trusting it makes
     *   {@code finish()} target the wrong Activity (or a null one) and silently
     *   no-op, leaving the user stuck.
     *
     * Instead we walk {@code android.app.ActivityThread.mActivities} for live
     * Activities whose class is named "VRActivity" and finish each — same
     * reflection pattern used for host-Activity lookup in ViroViewOpenXR.
     *
     * JS usage:
     *   NativeModules.VRLauncher?.exitVRScene();
     */
    @ReactMethod
    public void exitVRScene() {
        new Handler(Looper.getMainLooper()).post(() -> {
            try {
                Class<?> threadCls = Class.forName("android.app.ActivityThread");
                Object thread = threadCls.getMethod("currentActivityThread").invoke(null);
                java.lang.reflect.Field activitiesField = threadCls.getDeclaredField("mActivities");
                activitiesField.setAccessible(true);
                Object activities = activitiesField.get(thread);
                if (!(activities instanceof java.util.Map)) {
                    return;
                }
                for (Object record : ((java.util.Map<?, ?>) activities).values()) {
                    java.lang.reflect.Field activityField = record.getClass().getDeclaredField("activity");
                    activityField.setAccessible(true);
                    Object a = activityField.get(record);
                    if (!(a instanceof Activity)) continue;
                    Activity act = (Activity) a;
                    if (!"VRActivity".equals(act.getClass().getSimpleName())) continue;
                    if (act.isFinishing() || act.isDestroyed()) continue;
                    act.finish();
                }
            } catch (Throwable ignored) {}
        });
    }
}
